services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: workscrum
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env  # Monta el archivo .env dentro del contenedor


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workscrum
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistir datos
      - ./sql:/docker-entrypoint-initdb.d  # Montar la carpeta sql con los archivos .sql

volumes:
  db_data: